trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
# tag: 35

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        containerRegistry: 'jamaldockerhub'
        repository: 'jamalshahverdiev/currency-exchange'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - task: CopyFiles@2
      displayName: Copy file from current dir to target folder
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.yaml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: Publish Build Artifact
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'

# - stage: Deploy
#   displayName: Deploy image
#   jobs:  
#   - job: Deploy
#     displayName: Deploy
#     pool:
#       vmImage: 'ubuntu-latest'
#     steps:
#     - task: DownloadPipelineArtifact@2
#       displayName: Download Pipeline Artifact
#       inputs:
#         buildType: 'current'
#         artifactName: 'manifests'
#         itemPattern: '**/*.yaml'
#         targetPath: '$(System.ArtifactsDirectory)'
#     - task: KubernetesManifest@0
#       displayName: Deploy to Kubernetes
#       inputs:
#         action: 'deploy'
#         kubernetesServiceConnection: 'aws-kubrnetes-cluster-service-connection'
#         namespace: 'default'
#         manifests: '$(System.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml'
#         containers: in28min/currency-exchange-devops:$(tag)